from setuptools import setup, find_packages

setup(
    name='autoview',
    version='0.1.0',
    description='autoview: Effortless Exploratory Data Analysis with one line of code. Auto-summary, insights, and visualizations.',
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author='Avinash Betha',
    author_email='avinashb1581@gmail.com',
    url='https://github.com/avinash-betha/autoview',
    project_urls={
        'Documentation': 'https://github.com/avinash-betha/autoview',
        'Source': 'https://github.com/avinash-betha/autoview',
        'Tracker': 'https://github.com/avinash-betha/autoview/issues',
    },
    license='MIT',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Framework :: Jupyter',
        'Environment :: Console',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Utilities',
    ],
    packages=find_packages(exclude=["tests*", "examples*"]),
    include_package_data=True,
    install_requires=[
        'pandas>=1.0',
        'seaborn>=0.11',
        'matplotlib>=3.3',
        'tabulate>=0.8',
        'missingno>=0.5',
        'scikit-learn>=0.24'
    ],
    keywords="EDA, auto EDA, data analysis, data visualization, pandas, data science, autoview, exploratory analysis",
    python_requires='>=3.6',
)
